# Generated by Django 4.0.3 on 2022-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=10000, verbose_name='Содержание')),
                ('image', models.ImageField(height_field='500', null=True, upload_to='images/', width_field='500')),
            ],
            options={
                'ordering': ['date_published'],
            },
        ),
    ]
