# Generated by Django 4.0.3 on 2022-03-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(height_field='500', null=True, upload_to='static/images/', width_field='500'),
        ),
    ]
